name: yes

on:
  workflow_dispatch:
  push:
    branches: [ testing ]

env:
  KERNEL_BRANCH: testing

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: yes
      run:
        ls | tee yes.txt
    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
          name: yes
          path: yes.txt
